version: '3.1'

services:

    prometheus:
        network_mode: host
        build: prometheus
        ports:
            - '9090:9090'

    grafana:
        network_mode: host
        build: grafana
        depends_on:
            - prometheus
        ports:
            - '3000:3000'

